<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="./style24.css" type="text/css"/>
        <title>calendrier</title>
    </head>

    <body>
        <div id="bloc_page">
            <div id="gauche">
                <h1>Jour 24: Derniere surprise</h1>
                <h2>Find de l'histoire</h2>
                <p>
 L’heure tourne mais les voitures n’avancent pas plus. Le chauffeur regarde dans son rétroviseur intérieur son passager : les yeux de ce jeune européen ne cessent de faire des aller-retours entre le cadran de sa montre et la file d’automobilistes. Il semble stressé, pour ne pas dire angoissé.
Et Alexis Roselier l’est. Il a choisi d’écouter le conducteur, et de jouer le tout pour le tout. Sûr de sa décision, il ne peut toutefois s’empêcher d’être saisi des mêmes peurs qui le paralysent toujours face à l’imprévisible. Il regrette amèrement le confortable fauteuil de ce bureau à Paris où il supervise depuis quelques semaines l’équipe qui l’aide à ficeler ce projet. Il regrette le confort d’un planning sans imprévu, d’un trajet quotidien sans aléas, d’une vie sans encombre. Depuis son arrivée en Arabie Saoudite, pas une journée ne s’est écoulée sans qu’il ait à prendre une décision pénible. Il se demande combien son métier est fragile, combien son assurance n’est pas superficielle. Lui qui avait suivi tous les conseils, répété tous les mots qu’il fallait dire, lui qui s’était toujours attelé avec patience et rigueur à se construire la vie idéale, la vie parfaite, la vie comblée, il se trouvait bien malheureux et impuissant tout à coup. Immobile dans ce taxi immobile, il voit les gens s’agiter dans leurs voitures, il entend ces klaxons, et attend patiemment que les aiguilles sur sa montre ralentissent la cadence. Mais elles ne ralentissent pas. Non, le temps avance quoi qu’il advienne. La vie bat son plein même lorsque l’homme fait une pause. Au fond, l’homme n’est maître que de bien peu de choses.
Pourtant, il pense à cette famille qu’il a rencontrée au début du voyage, gérant un hôtel au bord de la faillite, souffrant de trop de générosité envers ses clients. Il songe à ce chauffeur de taxi prêt à arrêter son métier de passion pour profiter de chaque instant que la vie donne à une femme gravement malade. Il pense à toutes ces personnes qui ont croisé son chemin depuis le début de son périple, à tous ces visages, ces yeux et ces sourires. Dans leur malheur et leur pauvreté, tous ces gens partageaient pourtant la même force de vivre, ce même ’’je-ne-sais-quoi’’ qu’on appelle le bonheur. Pourquoi se trouvait-il si différent d’eux, lui qui avait famille, maison et travail ? Comment pouvait-il se trouver si fragile à l’apogée d’une carrière dont il avait tant rêvé ? Épuisé par tant de questions, éreinté par ce voyage qui ne semblait connaître aucune fin, Alexis Roselier s’endort.
Doha, Hôtel Crowne Plaza Doha. Le chauffeur de taxi avait vu juste : en convenant d’un rendez-vous à mi-chemin, il pouvait faire sa réunion à temps. Il n’avait pas vu comment le chauffeur était miraculeusement sorti des embouteillages, ni avec quel empressement il avait fait le plein pour être sûr que son client arrive à temps. Mais il était là, entouré de ses collaborateurs, à l’heure prévue et non loin du Doha Airport où il prendrait l’avion dans quelques heures. Ses économies, il avait finalement décidé de faire l’impasse dessus en finançant la venue des collaborateurs jusqu’à Doha. Certes, il aurait pu offrir beaucoup de choses avec cet argent, mais, désespérant sur la banquette arrière de son taxi, il avait finalement compris que rien n’était plus précieux que le temps. L’argent se gagne mais le temps ne se rattrape pas. Il gagnerait donc de l’argent plus tard. Pour l’heure, il était déterminé : avec ou sans contrat, il serait à la maison à temps pour Noël.
Alexis Roselier avait appris beaucoup de choses durant son voyage, mais surtout, il avait compris ce qu’était le bonheur, du moins le pensait-il. Pas une personne qu’il avait croisée sur son chemin n’avait le même destin qu’une autre. Pourtant, chacune à sa manière avait réussi à se frayer un chemin dans ce tortueux chemin de la vie. Ce qu’elles partageaient était plus grand que n’importe quel obstacle qui frappe de plein fouet la vie d’un homme, d’un couple ou d’une famille : l’intime conviction qu’en se battant pour les causes en lesquelles on croit, on sort toujours vainqueur du combat. Au fond, ce qui est le plus important, ce n’est pas qu’un hôtel se transmette de générations en générations jusqu’à la fin des temps, pas plus que de créer une vie éternelle. Ce qui est important, c’est ce que l’on tire de l’existence de cet hôtel, c’est ce que l’on retient de la vie d’une femme : les souvenirs.
                </p> 
            </div>
            <div id="droite">
                <p>
Au même instant, près de Dubaï, un homme se battait pour ses souvenirs. Les intempéries avaient inondé la maison du négociateur à un point tel qu’il devait l’évacuer avant d’être pris en charge, avec sa famille, dans un hôtel. Il n’avait pas attendu qu’Alexis Roselier l’appelle pour annuler la réunion, il s’en était chargé lui-même. Conscient qu’un deuxième voyage en ces périodes de fêtes était inenvisageable, et convaincu que la ville de Dubaï ne pourrait accepter un mois de retard dans l’inauguration d’un tel projet, il accepta finalement le projet sur la seule base des rapports écrits qui lui avaient été envoyés, et s’empressa de raccrocher. Ni Alexis ni ses collaborateurs n’eurent le temps de réaliser la tournure que prenaient les événements que le contrat était ficelé. Eux qui quelques minutes auparavant doutaient encore de la possibilité d’un tel contrat peinèrent à expliquer au supérieur d’Alexis Roselier qu’une telle situation ait pu se produire. Et lorsque Alexis demanda à son chef pourquoi ce voyage était censé être nécessaire si le contrat pouvait être signé sans réunion, il lui répondit :
« Dans le domaine de l’immobilier, on ne peut s’engager sans connaître la personne avec qui on travaille. Votre volonté d’aller jusqu’à sa rencontre malgré les intempéries, les fêtes de Noël et les embouteillages, même si vous avez in extremis changé de décision, l’a convaincu que vous étiez cet homme sérieux, ambitieux et impliqué avec lequel on mène les plus grands projets »
Ainsi, son ambition l’avait mené jusqu’au bout de ses rêves, et ses choix l’amèneraient bientôt à la maison pour fêter Noël à temps.
Derrière le hublot, Alexis Roselier est serein. Au dessus de cette terre des imprévus, flottant dans ce ciel plein de surprises, il a trouvé le calme qu’il avait toujours cherché à conquérir. Il ne sait pas plus voler que depuis le début de son voyage, mais il sait maintenant écouter le doux son de la liberté. Il faut croire que les philosophes avaient raison: c’est dans ses rêves que l’homme trouve la liberté. C’est dans ses rêves que l’homme trouve sa liberté. 
Peut-être aura-t-il encore des contraintes, des obligations, des exigences à satisfaire. Peut-être que certains matins, il doutera. Mais il sait que partout où il ira, quoi qu’il fera, il sera libre. Libre d’aimer sa femme, libre de voir grandir ses enfants, libre d’être heureux de ces petits conforts qu’il n’avait jamais appréciés à leur juste valeur jusque là. Face à la pauvreté et aux coups du destin, ces gens qu’il n’avait jamais enviés lui avaient finalement donné tort: n’est libre que celui qui veut se sentir libre.
Derrière le hublot, Alexis Roselier est libre parce qu’il le sait: dans quelques minutes, il atterrira. Et dans quelques heures, il préparera la dinde, il emballera les cadeaux, il embrassera sa femme et plus tard, sa femme et lui contempleront, ensemble, cet album de photos qui immortalisera l’événement.
Histoires co-écrites par Coraline Staub-Milants et Viviana Hirsch
                </p> 
            </div>
        </div>
        <h2>Deux photos</h2>
        <img src="images/village6.jpg">
        <img src="images/village7.jpg">
        <h2>Solution enigme</h2>
        <img src="images/square.png" id="square">
    </body>
</html>
